services:
  frontend:
    image: ghcr.io/h4shu/shiritori-go-frontend
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_BASEURL=https://${KOYEB_PUBLIC_DOMAIN}/api

  backend:
    image: ghcr.io/h4shu/shiritori-go-backend
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD
      - PORT=8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379