services:
  frontend:
    build:
      context: ./frontend
      platforms:
        - linux/amd64
        - linux/arm64
    image: h4shu/shiritori-go-frontend

  backend:
    build:
      context: ./backend
      platforms:
        - linux/amd64
        - linux/arm64
    image: h4shu/shiritori-go-backend