services:
  frontend:
    build: ./frontend
    image: shiritori-go-frontend
    environment:
      - VITE_BACKEND_BASEURL=http://localhost:8080
    volumes:
      - ./frontend/src:/app
      - /src/node_modules
    ports:
      - 5173:5173

  backend:
    build: ./backend
    image: shiritori-go-backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD
      - PORT=8080
    depends_on:
      - redis
    ports:
      - 8080:8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379