name: Deploy to Koyeb

on:
  push:
    branches: [ "main" ]

jobs:
  go-build:
    uses: ./.github/workflows/go.yml

  docker-build-push:
    permissions:
      packages: write
    needs: go-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        run: docker compose -f docker-compose.build.yml build --no-cache --push

  koyeb-deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: "shiritori-go"
          privileged: "true"
          git-builder: "docker"
          git-docker-dockerfile: "Dockerfile.koyeb"
          service-instance-type: "free"
          service-regions: "was"
          service-ports: "5173:http,8080:http"
          service-routes: "/:5173,/api:8080"
          service-checks: "5173:tcp,8080:tcp"
